pipeline:
  sftp_cache:
    image: plugins/sftp-cache
    restore: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier
      - /drone/.sbt
      - /drone/.git

  build:
    image: scalacenter/scala:1.1
    commands:
      - sbt clean

  sftp_cache:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - /drone/.ivy2
      - /drone/.coursier
      - /drone/.sbt
      - /drone/.git
